openapi: '3.0.2'
info:
  title: 'Delivery-service'
  description: 'Delivery-service API description'
  version: '0.0'
components:
  schemas:
    Order:
      type: object
      properties:
        x_d:
          type: string

    OrderCreated:
      type: object
      properties:
        order_id:
          type: string

    Delivery_price_req:
      type: object
      properties:
        start:
          type: string
        end:
          type: string

paths:
  /ping:
    get:
      tags:
        - Tech
      summary: Ping service
      responses:
        '429':
          description: Too many requests
        '200':
          description: Ok. Service is available

  /api/v1/orders:
    get:
      tags:
        - Orders
      summary: get orders list
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        '400':
          description: Bad parameters
        '429':
          description: Too many requests
        '500':
          description: Internal server error
    post:
      tags:
        - Orders
      summary: add order
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderCreated'
        '400':
          description: Bad parameters
        '429':
          description: Too many requests
        '500':
          description: Internal server error

  /api/v1/orders/{order_id}:
    get:
      tags:
        - Orders
      summary: delete orders
      parameters:
        - name: order_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '404':
          description: Not found
        '429':
          description: Too many requests
        '500':
          description: Internal server error
    delete:
      tags:
        - Orders
      summary: delete order
      parameters:
        - name: order_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Ok
        '404':
          description: Not found
        '429':
          description: Too many requests
        '500':
          description: Internal server error


  /api/v1/orders/{order_id}/status:
    patch:
      tags:
        - Orders
      summary: Update status
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order' # Enum status
      parameters:
        - name: order_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Ok
        '404':
          description: Not found
        '429':
          description: Too many requests
        '500':
          description: Internal server error

  /api/v1/delivery/price:
    post:
      tags:
        - Delivery
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Delivery_price_req'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order' # Price
        '429':
          description: Too many requests
        '406':
          description: Not acceptable content
        '500':
          description: Internal server error
