"""initial

Revision ID: ac05757cb1ff
Revises: 
Create Date: 2021-12-12 13:04:48.673806

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ac05757cb1ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('content', sa.String(length=60), nullable=False),
    sa.Column('comment', sa.String(length=60), nullable=False),
    sa.Column('state', postgresql.ENUM('RECEIVED', 'TAKEN', 'DELIVERED', name='orderstate'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__Orders'))
    )
    op.create_table('Restaurants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('coords', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__Restaurants'))
    )
    op.create_table('Dishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('external_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['Restaurants.id'], name=op.f('fk__Dishes__restaurant_id__Restaurants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__Dishes'))
    )
    op.create_table('OrdersToDishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dish_id'], ['Dishes.id'], name=op.f('fk__OrdersToDishes__dish_id__Dishes')),
    sa.ForeignKeyConstraint(['order_id'], ['Orders.id'], name=op.f('fk__OrdersToDishes__order_id__Orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__OrdersToDishes'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('OrdersToDishes')
    op.drop_table('Dishes')
    op.drop_table('Restaurants')
    op.drop_table('Orders')
    # ### end Alembic commands ###
