"""made uuid unique

Revision ID: eada01d6e8b5
Revises: 19595991f6e2
Create Date: 2021-12-11 16:47:54.781841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eada01d6e8b5'
down_revision = '19595991f6e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq__Dishes__external_id'), 'Dishes', ['external_id'])
    op.create_unique_constraint(op.f('uq__Orders__external_id'), 'Orders', ['external_id'])
    op.create_unique_constraint(op.f('uq__Restaurants__external_id'), 'Restaurants', ['external_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__Restaurants__external_id'), 'Restaurants', type_='unique')
    op.drop_constraint(op.f('uq__Orders__external_id'), 'Orders', type_='unique')
    op.drop_constraint(op.f('uq__Dishes__external_id'), 'Dishes', type_='unique')
    # ### end Alembic commands ###
