DEFAULT_PORT = 8080

DEFAULT_MAX_RPS = 0

DEFAULT_LOG_FILE = None
DEFAULT_LOG_LEVEL = 'INFO'

DEFAULT_DB_PORT = 5432
DEFAULT_DB_HOST = 'localhost'
DEFAULT_DB_USER = 'postgres'
DEFAULT_DB_PASSWORD = 'postgres'
DEFAULT_DB_NAME = 'db'