DEFAULT_PORT = 8080

DEFAULT_MAX_RPS = 0

DEFAULT_LOG_FILE = None
DEFAULT_LOG_LEVEL = 'INFO'

DEFAULT_DB_PORT = 5432
DEFAULT_DB_HOST = 'localhost'
DEFAULT_DB_USER = 'postgres'
DEFAULT_DB_PASSWORD = 'postgres'
DEFAULT_DB_NAME = 'db'

DEFAULT_API_KEY = None
DEFAULT_MONEY_FOR_METER = 0.1
DEFAULT_MIN_COST = 400
DEFAULT_GEO_API_MODE = 'EXTERNAL_API'
